use AppForFindJob
go
CREATE TABLE TB_ACCOUNT
(
	ID_ACCOUNT NVARCHAR(10) NOT NULL,
	USERNAME NVARCHAR(20) NOT NULL,
	PASSWORD NVARCHAR(20) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	ACCESSER SMALLINT NOT NULL,
	STATUS BIT NOT NULL

	CONSTRAINT PK_TB_ACCOUNT PRIMARY KEY (ID_ACCOUNT)
)
CREATE TABLE TB_SEEKER_PROFILE
(
	ID_ACCOUNT NVARCHAR(10) NOT NULL,
	FIRST_NAME NVARCHAR(20) NOT NULL,
	LAST_NAME NVARCHAR(20) NOT NULL,
	AGE SMALLINT NOT NULL,
	GENDER BIT NOT NULL,
	CV NVARCHAR(200),
	IMAGE NVARCHAR(MAX),
	PHONE_NUMBER NVARCHAR(15),
	SEEKER_DESCRIPTION NVARCHAR(MAX),
	FACEBOOK NVARCHAR(200)

	CONSTRAINT PK_TB_SEEKER_PROFILE PRIMARY KEY(ID_ACCOUNT),
	CONSTRAINT FK_ID_ACCOUNT_TB_SEEKER_PROFILE FOREIGN KEY(ID_ACCOUNT) REFERENCES TB_ACCOUNT(ID_ACCOUNT)
)
CREATE TABLE TB_SKILL
(
	ID_SKILL NVARCHAR(10) NOT NULL,
	NAME_SKILL NVARCHAR(50) NOT NULL

	CONSTRAINT PK_TB_SKILL PRIMARY KEY(ID_SKILL)
)
CREATE TABLE TB_SELECTED_SKILL
(
	ID_SKILL NVARCHAR(10) NOT NULL,
	ID_ACCOUNT NVARCHAR(10) NOT NULL,
	LEVEL_SKILL SMALLINT NOT NULL

	CONSTRAINT PK_TB_SELECTED_SKILL PRIMARY KEY (ID_SKILL, ID_ACCOUNT),
	CONSTRAINT FK_ID_SKILL_TB_SELECTED_SKILL FOREIGN KEY(ID_SKILL) REFERENCES TB_SKILL(ID_SKILL),
	CONSTRAINT FK_ID_ACCOUNT_TB_SELECTED_SKILL FOREIGN KEY(ID_ACCOUNT) REFERENCES TB_SEEKER_PROFILE(ID_ACCOUNT)
)
CREATE TABLE TB_EMPLOYER_PROFILE
(
	ID_ACCOUNT NVARCHAR(10) NOT NULL,
	COMPANYNAME NVARCHAR(200) NOT NULL,
	COMPANY_DESCRIPTION NVARCHAR(MAX),
	WEBSITE NVARCHAR(200)

	CONSTRAINT PK_TB_EMPLOYER_PROFILE PRIMARY KEY (ID_ACCOUNT)
)
CREATE TABLE TB_IMAGE
(
	ID_ACCOUNT NVARCHAR(10) NOT NULL,
	ID_IMAGE NVARCHAR(10) NOT NULL,
	IMAGE NVARCHAR(200) NOT NULL,

	CONSTRAINT PK_TB_IMAGE PRIMARY KEY (ID_IMAGE),
	CONSTRAINT FK_TB_IMAGE_TB_IMAGE FOREIGN KEY(ID_ACCOUNT) REFERENCES TB_ACCOUNT(ID_ACCOUNT)
)
CREATE TABLE TB_ADDRESS
(
	ID_ADDRESS NVARCHAR(10) NOT NULL,
	COUNTRY NVARCHAR(100) NOT NULL,
	CITY NVARCHAR(100) NOT NULL

	CONSTRAINT PK_TB_ADDRESS PRIMARY KEY (ID_ADDRESS)
)
CREATE TABLE TB_POST
(
	ID_ACCOUNT NVARCHAR(10) NOT NULL,
	ID_POST NVARCHAR(10) NOT NULL,
	JOB_TITLE NVARCHAR(200) NOT NULL,
	ID_ADDRESS NVARCHAR(10) NOT NULL,
	JOB_DESCRIPTION NVARCHAR(MAX),
	STATUS BIT

	CONSTRAINT PK_TB_POST PRIMARY KEY (ID_POST),
	CONSTRAINT FK_ID_ACCOUNT_TB_POST FOREIGN KEY (ID_ACCOUNT) REFERENCES TB_EMPLOYER_PROFILE(ID_ACCOUNT),
	CONSTRAINT FK_ID_ADDRESS_TB_POST FOREIGN KEY (ID_ADDRESS) REFERENCES TB_ADDRESS(ID_ADDRESS)
)
CREATE TABLE TB_ACCOUNT_APPLY
(
	ID_POST NVARCHAR(10) NOT NULL,
	ID_ACCOUNT NVARCHAR(10) NOT NULL,

	CONSTRAINT PK_TB_ACCOUNT_APPLY PRIMARY KEY (ID_POST, ID_ACCOUNT),
	CONSTRAINT FK_ID_POST_TB_ACCOUNT_APPLY FOREIGN KEY (ID_POST) REFERENCES TB_POST(ID_POST),
	CONSTRAINT FK_ID_ACCOUNT_TB_ACCOUNT_APPLY FOREIGN KEY (ID_ACCOUNT) REFERENCES TB_SEEKER_PROFILE(ID_ACCOUNT)
)
ALTER TABLE TB_SELECTED_SKILL DROP COLUMN LEVEL_SKILL

DROP TABLE TB_SKILL
DROP TABLE TB_SELECTED_SKILL
DROP TABLE TB_SEEKER_PROFILE
DROP TABLE TB_ADDRESS
DROP TABLE TB_ACCOUNT_APPLY
DROP TABLE TB_IMAGE
DROP TABLE TB_POST
DROP TABLE TB_EMPLOYER_PROFILE
DROP TABLE TB_ACCOUNT

SELECT * FROM TB_ACCOUNT WHERE USERNAME = 'LHM2K1' and PASSWORD = 'LHM2K1' and STATUS = 'True'